name: Build, lint and test

on:
  push:
    branche: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_neural_network:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cd libs/neural-network
      - uses: actions-rs/cargo@v1
        with:
          command: check

  lint_neural_network:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cd libs/neural-network
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -Dwarnings

  test_neural_network:
    runs-on: ubuntu-latest
    needs: [build, lint]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cd libs/neural-network
      - uses: actions-rs/cargo@v1
        with:
          command: test
